# Generated by Django 2.2.4 on 2021-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla_app', '0002_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='movie',
            field=models.IntegerField(default=123456789123456789),
            preserve_default=False,
        ),
    ]
