# Generated by Django 2.2.4 on 2021-04-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla_app', '0004_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.IntegerField(default=123456789132456123456),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
