# Generated by Django 2.2.4 on 2021-04-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla_app', '0006_auto_20210430_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
